# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-DBH
version:      0.11
version_from: lib/DBIx/DBH.pm
installdirs:  site
requires:
    DBI:                           1.3
    Params::Validate:              0.7

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
